### ISSUE TITLE
Вопрос по lab_1

### ISSUE THREAD

**Issue by smorshchek** [BSU2013gr0209web/Workflow#2]
@HaraldZealot 
Добрый день. А Вы не могли бы подсказать, почему стоят вопросы по первой лабораторной?

**Comment by HaraldZealot** [comment]
Таму што у мяне гэта выглядае прыблізна вось так
![snp33](https://cloud.githubusercontent.com/assets/1811725/6919620/44d4fa26-d7c1-11e4-9990-7f76d7cb6e26.png)

А на кнопкі ніяк не рэагуе, з першым прылажэннем тое самае.
