### ISSUE TITLE
Не засчитанная 2 лабораторная, из-за отсутствия .gitignore

### ISSUE THREAD

**Issue by Zwi17** [BSU2013gr0209web/Workflow#3]
У меня отсутствует .gitignore в моём репозитории здесь, но есть у меня в папке.
Может быть вы в этот раз всё-таки простите, а, как только появится доступ, я добавлю его сюда.

**Comment by kaban4eek** [comment]
Пожалуйста откройте доступ.пусть это будет предупреждением.потому что выскочило из головы. И даже об этом не вспомнил.какие может много других людей.пусть первый и последний раз
